// Mocks generated by Mockito 5.0.17 from annotations
// in renofax/test/features/complaints/data/repositories/complaint_respository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:renofax/core/network/network_info.dart' as _i5;
import 'package:renofax/features/complainant/data/data_sources/complaint_remote_data_source.dart'
    as _i3;
import 'package:renofax/features/complainant/data/models/complaint.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeComplaint_0 extends _i1.Fake implements _i2.Complaint {}

/// A class which mocks [ComplaintRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockComplaintRemoteDataSource extends _i1.Mock
    implements _i3.ComplaintRemoteDataSource {
  MockComplaintRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Complaint>> getComplaints() =>
      (super.noSuchMethod(Invocation.method(#getComplaints, []),
              returnValue: Future<List<_i2.Complaint>>.value(<_i2.Complaint>[]))
          as _i4.Future<List<_i2.Complaint>>);
  @override
  _i4.Future<_i2.Complaint> getComplaintById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getComplaintById, [id]),
              returnValue: Future<_i2.Complaint>.value(_FakeComplaint_0()))
          as _i4.Future<_i2.Complaint>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
