name: renofax
description: Management Property Apps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  chopper: ^4.0.4
  connectivity: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  color: ^3.0.0
  google_maps_flutter: ^2.1.2



dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
